name:                seal-prelude
version:             1.0.0
github:              https://github.com/sealchain/seal-prelude
license:             BSD3
author:              hanfei
maintainer:          example@example.com
copyright:           2019 hanfei

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hanfei-hank/hclj#readme>

dependencies:
- ansi-wl-pprint >= 0.6.7.3 && < 0.7
- attoparsec >= 0.13.0.2 && < 0.14
- base
- base16-bytestring >=0.1.1.6 && < 0.2
- bytestring >=0.10.8.1 && < 0.11
- compactable >= 0.1 && < 0.2
- containers >= 0.5.7 && < 0.6
- data-default >= 0.7.1.1 && < 0.8
- deepseq >= 1.4.2.0 && < 1.5
- exceptions >= 0.8.3 && < 0.11
- hashable >= 1.2.4.0 && < 1.3
- lens >= 4.14 && <= 4.18
- lens-aeson >= 1.0.0.5 && < 1.1
- megaparsec >= 6
- mtl >= 2.2.1 && < 2.3
- old-locale >= 1.0.0.7 && < 1.1
- optparse-applicative >= 0.12.1.0 && < 0.15
- parsers >= 0.12.4 && < 0.13
- rio
- safe >= 0.3.11 && < 0.4
- scientific >= 0.3.4.9 && < 0.4
- semigroups >= 0.18.2 && < 0.19
- stm >= 2.4.4.1 && < 2.6
- template-haskell
- text >= 1.2.2.1 && < 1.3
- thyme == 0.3.6.0
- trifecta >= 2 && < 2.1
- unliftio
- universum
- unix
- unordered-containers >= 0.2.7.2 && < 0.3
- utf8-string >= 1.0.1.1 && < 1.1
- vector >= 0.11.0.0 && < 0.13
- vector-space >= 0.10.4 && < 0.16
- yaml

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies: []
  default-extensions:
  - BangPatterns
  - DeriveGeneric
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns